---

- name: ensure that /etc/cron.daily is present
  ansible.builtin.file:
    state: directory
    path: /etc/cron.daily
    mode: 0755

- name: write cron.daily
  ansible.builtin.template:
    src: cron_logrotate.j2
    dest: /etc/cron.daily/logrotate
    mode: 0755

...
